name: JS Actions

on:
  workflow_dispatch:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ['raftik', 'hakan', '999']
        sex: ['male']
        location: ['istanbul', 'riga', 'amsterdam']

    steps:
      - uses: actions/checkout@v4

      - name: ha-ha
        uses: ./.github/actions/joke-action
        id: joke
        with:
          name: ${{ matrix.name }}

      - name: repeat-joke
        run: echo "$JOKE"
        env:
          JOKE: "${{ steps.joke.outputs.joke-output }}"
